# Generated by Django 5.2.6 on 2025-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0014_alter_emergencynotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyresponse',
            name='status',
            field=models.CharField(choices=[('notified', 'Notified'), ('dispatched', 'Dispatched'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='notified', max_length=20),
        ),
    ]
